# Generated by Django 4.0.6 on 2022-10-03 09:13
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_team',
            name='postingDate',
            field=models.DateTimeField(default=lambda: datetime.datetime.now(datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
