# Generated by Django 5.2.1 on 2025-05-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_add_team_postingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_team',
            name='team_member',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident_report',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
