# Generated by Django 5.2.1 on 2025-05-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_add_team_team_member_alter_fire_report_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident_history',
            old_name='incidentreport',
            new_name='inicdentreport',
        ),
    ]
